name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mac:
    name: macOS
    runs-on: macOS-15
    steps:
    - uses: actions/checkout@v3
    - name: Swift Version
      run: swift --version
    - name: Run Tests
      run: make test-library

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: make DOCKER_PLATFORM=linux/amd64 test-linux
