name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mac:
    name: macOS
    runs-on: macOS-15
    strategy:
      matrix:
        xcode: ['14.2']
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Swift Version
      run: swift --version
    - name: Run ${{ matrix.xcode }} Tests
      run: make test-library

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.10
    - uses: actions/checkout@v3
    - name: Run Tests
      run: make DOCKER_PLATFORM=linux/amd64 test-linux
